export const randomSite = Math.floor(Math.random()*3);

export const ilustrations = [
    {
        name: 'Jam',
        id: 0,
        url: 'food-jam.webp',
        description: 'Color Wheel',
        src: 'illustration-0-colorWheel.webp',
        stack: 'ai',
        wid: '484',
        heig: '317',
    },
    {
        name: 'CatBurger',
        id: 1,
        url: 'food-burger.webp',
        description: 'McMiku',
        src: 'illustration-1-mcMiku.webp',
        stack: 'ai',
        wid: '644',
        heig: '412',
    },
    {
        name: 'Malteada',
        id: 2,
        url: 'food-milkshake.webp',
        description: 'Ai Hoshino',
        src: 'illustration-2-ai-hoshino.webp',
        stack: 'ai',
        wid: '303',
        heig: '452',
    },
    {
        name: 'Ice Cream',
        id: 3,
        url: 'food-icecream.webp',
        description: 'Sakura Miku',
        src: 'illustration-3-sakuraMiku.webp',
        stack: 'ai',
        wid: '429',
        heig: '381',
    },
    {
        name: 'Candy',
        id: 4,
        url: 'food-lollipop.webp',
        description: 'Haerin',
        src: 'illustration-4-haerin.webp',
        stack: 'ai',
        wid: '251',
        heig: '307',
    },
    {
        name: 'Macarron',
        id: 5,
        url: 'food-macaroon.webp',
        description: 'Miku Monalisa',
        src: 'illustration-5-strawberryMiku.webp',
        stack: 'ai',
        wid: '524',
        heig: '364',
    },
    {
        name: 'Juice',
        id: 6,
        url: 'food-juice.webp',
        description: 'Miku Popipo',
        src: 'illustration-6-popipoMiku.webp',
        stack: 'ai',
        wid: '346',
        heig: '429',
    },
]

export const colorBalls = [
    'url(contact/ball/ball-green.webp)',
    'url(contact/ball/ball-purple.webp)',
    'url(contact/ball/ball-rouse.webp)',
    'url(contact/ball/ball-blue.webp)',
]

export const randomQuotes = [
    'I really like the virtual diva Hatsune Miku, she is my inspiration.',
    'I have always liked to draw, but it was not until recently that I wanted to be an illustrator.',
    'I love sweet food, but donuts take first place...for now.',
    'In addition to illustrating, I like to create and paint 3D figures.',
    'I like purple and pink, but pastel yellow and green too.',
    'I am fascinated by miniature food figures and nendoroids. I am trying to collect them.',
    'Although my strongest skill is illustration, creative writing is my second job.',
    "Spanish is my native language. I know a little English and I'm currently learning Japanese.",
    'I like horror and scary games, the kind that make you scream and then laugh.',
    "...and that's why my biggest fear is seeing a dog eating cereal with a spoon.",
]